name: crypto_psycho
description: A new crypto project CryptoPsycho.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  retrofit: ^3.0.1+1
  pull_to_refresh: ^2.0.0
  injectable: ^1.5.3
  dio: ^4.0.6
  get_it: ^7.2.0
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.0.3+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  freezed: ^2.1.0+1
  injectable_generator:

flutter:
  uses-material-design: true
